language: node_js
node_js:
  - 4.1
before_script:
  - npm install -g grunt-cli
  - npm install -g jasmine-node
branches:
  only:
    - master
script:
  - grunt test
notifications:
  email:
    recipients:
      - support@globexdesigns.com
