"use strict";

var base = 'doby-grid';

module.exports = {
	autoheight:				base + '-autoheight',
	canvas:					base + '-canvas',
	cell:					base + '-cell',
	cellunselectable:		base + '-cell-unselectable',
	clipboard:				base + '-clipboard',
	collapsed:				'collapsed',
	columnname:				base + '-column-name',
	columnspacer:			base + '-column-spacer',
	contextmenu:			base + '-contextmenu',
	dropdown:				base + '-dropdown',
	dropdownmenu:			base + '-dropdown-menu',
	dropdownitem:			base + '-dropdown-item',
	dropdowndivider:		base + '-dropdown-divider',
	dropdownarrow:			base + '-dropdown-arrow',
	dropdownicon:			base + '-dropdown-icon',
	dropdownleft:			base + '-dropdown-left',
	dropdowntitle:			base + '-dropdown-title',
	editor:					base + '-editor',
	empty:					base + '-empty',
	expanded:				'expanded',
	garbage:				'DobyGridGarbageBin',
	group:					base + '-group',
	grouptitle:				base + '-group-title',
	grouptoggle:			base + '-group-toggle',
	gutter:					base + '-gutter',
	guttersVisible:			base + '-gutters-visible',
	handle:					base + '-resizable-handle',
	header:					base + '-header',
	headercolumns:			base + '-header-columns',
	headercolumn:			base + '-header-column',
	headercolumnactive:		base + '-header-column-active',
	headercolumndrag:		base + '-header-column-dragging',
	headercolumnsorted:		base + '-header-column-sorted',
	headerfilter:			base + '-header-filter',
	headerfiltercell:		base + '-header-filter-cell',
	headerfilterdisabled:	base + '-header-filter-disabled',
	headersortable:			'sortable',
	invalid:				'invalid',
	invalidicon:			base + '-invalid-icon',
	left:					base + '-scrollbar-left',
	noright:				base + '-no-right',
	pane:					base + '-pane',
	paneactive:				base + '-pane-active',
	placeholder:			base + '-sortable-placeholder',
	rangedecorator:			base + '-range-decorator',
	rangedecoratorstat:		base + '-range-decorator-stats',
	row:					base + '-row',
	rowdragcontainer:		base + '-row-drag-container',
	rowhandle:				base + '-row-handle',
	rowtotal:				base + '-row-total',
	scrollloader:			base + '-scroll-loader',
	sortindicator:			base + '-sort-indicator',
	sortindicatorasc:		base + '-sort-indicator-asc',
	sortindicatordesc:		base + '-sort-indicator-desc',
	sticky:					base + '-sticky',
	tooltip:				base + '-tooltip',
	tooltiparrow:			base + '-tooltip-arrow',
	viewport:				base + '-viewport'
};
